### ISSUE TITLE
independent study planning

### ISSUE THREAD

**Issue by nicholustintzaw** [nutriverse/riycf#5]
Draft the project planning document to submit and @ernestguevarra Could you please review it? 

I am not able to make the pull request. So, I put it here for your review (not sure it is a good practice or not). I also found one r-project on complementary feeding indicators, and below was the link. It seems it was based on their in-house data project related to IYCF and not updated yet with the 2021 guideline. I think we are still valid to do this project as that one is not covered all the IYCF indicators. What do you think? 

https://tech.popdata.org/pma-data-hub/posts/2021-10-01-nutrition-indicators/#mdd-minimum-dietary-diversity

**Comment by ernestguevarra** [comment]
Hi @nicholustintzaw. It is ok to put this here but I can't see where the document is?

**Comment by nicholustintzaw** [comment]
Sorry, it is an RMD file.  riycf_planning.RMD

**Comment by ernestguevarra** [comment]
> Sorry, it is an RMD file. riycf_planning.RMD @ernestguevarra

Ok. Where can I find the Rmd?

**Comment by nicholustintzaw** [comment]
it is in the main code folder. just after riycf.Rproj

**Comment by ernestguevarra** [comment]
> > Sorry, it is an RMD file. riycf_planning.RMD @ernestguevarra
> 
> Ok. Where can I find the Rmd?

Ok. I see it now.

For next time, my suggestion is to make a separate repo for docs like this and call it by the name of the document and you should create the repo in your GitHub Account.

For this one since you pushed it into the package already, my suggestion is to put it inside a directory that you will add to .Rbuildignore.

**Comment by ernestguevarra** [comment]
> I see. let me remove and put it back to a separate repo, after you review it. thanks.

Also, if you want me to review something on this package through a pull request, you need to make sure you are working on a branch rather than on main/master. If you push to main/master, you are basically saying that is the final piece of work already and no one needs to review it. That is why you cannot create a pull request on main/master.

**Comment by ernestguevarra** [comment]
> I see. let me remove and put it back to a separate repo, after you review it. thanks.

@nicholustintzaw, I think it is better for you to remove it first, create a repo specific to that and then ask me to review that repo. Right now, for me to review your Rmd requires me to clone the package and review your Rmd from the package structure. This is not really ideal.

Also, when you ask someone to review an Rmd, it is best practice to provide both the Rmd and the output of the Rmd for review. Here, you set it up as an HTML with pagination to make it look like a document. So, I would like to see the output of this as well.

**Comment by nicholustintzaw** [comment]
Hi @ernestguevarra , I removed that rmd and put it back into the new repo. I invite you as a collaborator. But, not opened yet the issue as I can't mention you in that repo.

**Comment by ernestguevarra** [comment]
@nicholustintzaw see my feedback to your riycf_planning repository.

I am closing this now. we should continue any discussion regarding this in your riycf_planning repository
